<a href="https://colab.research.google.com/github/kjay94/Python-code/blob/main/k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
##Import libraries for data handling
import pandas as pd

In [7]:
#creating a list of lists, where each inner list represents a person's ratings for different items.
ratings=[['John',5,5,2,1],['Mary',4,5,3,2],['Bob',4,4,4,3],['Lisa',2,2,4,5],['Lee',1,2,3,4],['Harry',2,1,5,5]]

In [8]:
ratings

[['John', 5, 5, 2, 1],
 ['Mary', 4, 5, 3, 2],
 ['Bob', 4, 4, 4, 3],
 ['Lisa', 2, 2, 4, 5],
 ['Lee', 1, 2, 3, 4],
 ['Harry', 2, 1, 5, 5]]

In [9]:
#returns the data type of the variable ratings.
type(ratings)

list

In [10]:
#refers to the first element of the ratings list,
ratings[0]

['John', 5, 5, 2, 1]

In [11]:
#a list of strings, where each string represents a title.
titles=['User','Jaws','Star Wars','Exorcist','Omen']

In [12]:
#Display the titles
titles

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [13]:
# creates a Pandas DataFrame called movies using the ratings list and the titles list.
movies=pd.DataFrame(ratings, columns=titles)

In [14]:
#Displat the dataFrame
movies

User  Jaws  Star Wars  Exorcist  Omen
0   John     5          5         2     1
1   Mary     4          5         3     2
2    Bob     4          4         4     3
3   Lisa     2          2         4     5
4    Lee     1          2         3     4
5  Harry     2          1         5     5

In [15]:
#Import libraries for data clustering
from sklearn import cluster

In [16]:
#drops the column named "User" from the DataFrame and stores in a new variable called data.
data=movies.drop('User', axis=1)

In [17]:
#Display the new dataFrame called data
data

Jaws  Star Wars  Exorcist  Omen
0     5          5         2     1
1     4          5         3     2
2     4          4         4     3
3     2          2         4     5
4     1          2         3     4
5     2          1         5     5

In [18]:
#creates an instance of the K-Means clustering algorithm from the scikit-learn library.
k_means=cluster.KMeans(n_clusters=2, max_iter=100, random_state=1)

In [46]:
#variable k_means now holds an instance of the K-Means clustering algorithm
k_means

KMeans(max_iter=100, n_clusters=2, random_state=1)

In [20]:
#fits the K-Means clustering model to the data contained in the data variable.
k_means.fit(data)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(max_iter=100, n_clusters=2, random_state=1)

In [21]:
#retrieves the cluster labels assigned to each data point by the fitted K-Means model.
labels=k_means.labels_

In [22]:
#references the labels variable, which contains the cluster labels.
labels

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [23]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0   John     5          5         2     1
1   Mary     4          5         3     2
2    Bob     4          4         4     3
3   Lisa     2          2         4     5
4    Lee     1          2         3     4
5  Harry     2          1         5     5

In [24]:
#creates a new Pandas DataFrame called outcome. This DataFrame has two columns:
outcome=pd.DataFrame(labels, index=movies.User, columns=['Cluster ID'])


In [25]:
#The outcome variable is a Pandas DataFrame
outcome

Cluster ID
User             
John            1
Mary            1
Bob             1
Lisa            0
Lee             0
Harry           0

In [47]:
#The attribute of a KMeans object stores the coordinates of the cluster centers.
k_means.cluster_centers_
#Each row in the array represents a cluster, and each column in the array represents a feature.

array([[1.66666667, 1.66666667, 4.        , 4.66666667],
       [4.33333333, 4.66666667, 3.        , 2.        ]])

In [27]:
#a powerful library for scientific computing in Python.
import numpy as np

In [28]:
#It creates a NumPy array called testData that contains five rows and four columns.
testData=np.array([[4,5,1,2],[3,2,4,4],[3,2,4,1],[3,2,3,3],[5,4,1,4]])

In [29]:
#The testData variable is a NumPy array with five rows and four columns.
testData

array([[4, 5, 1, 2],
       [3, 2, 4, 4],
       [3, 2, 4, 1],
       [3, 2, 3, 3],
       [5, 4, 1, 4]])

In [30]:
#The type(testData) function returns the data type of the testData variable.
type(testData)

numpy.ndarray

In [31]:
#function uses the trained KMeans model to predict the cluster labels for the data points in the testData array.
labels_test=k_means.predict(testData)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [32]:
#variable is a NumPy array containing the predicted cluster labels for each data point in the testData array.
labels_test

array([1, 0, 1, 0, 1], dtype=int32)

In [33]:
#creates a NumPy array called userNames that contains five rows and one column.
userNames=np.array(['Maina','Tom','Joyce','Kamau','Otieno']).reshape(-1,1)

In [34]:
#The userNames variable is a NumPy array
userNames

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno']], dtype='<U6')

In [35]:
#reshapes the userNames array so that it has five rows and one column.
userNames.reshape(-1,1)

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno']], dtype='<U6')

In [36]:
#The userNames variable is a NumPy array with five rows and one column.
userNames

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno']], dtype='<U6')

In [37]:
#The labels variable is a NumPy array containing the predicted cluster labels for each data point in the testData array.
labels

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [38]:
#reshapes the labels_test array so that it has the same number of rows as the userNames array.
labels_test=labels_test.reshape(-1,1)

In [39]:
#is a NumPy array containing the predicted cluster labels for each data point in the testData array.
labels_test

array([[1],
       [0],
       [1],
       [0],
       [1]], dtype=int32)

In [40]:
# creates a list of all the column names in the movies DataFrame.
cols=movies.columns.tolist()

In [41]:
#The cols variable is a list containing the names of all the columns in the movies DataFrame.
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [42]:
#adds a new element to the end of the cols list. The new element is the string 'Cluster ID'.
cols.append('Cluster ID')

In [43]:
# is a list containing the names of all the columns in the movies DataFrame, plus the new 'Cluster ID' column.
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen', 'Cluster ID']

In [44]:
#code creates a new DataFrame called newUsers.
#The new DataFrame is created by concatenating three arrays along the first axis (axis 1):
#The userNames array
#The testData array
#The labels_test array
newUsers = pd.DataFrame(np.concatenate((userNames, testData,labels_test), axis=1), columns=cols)

In [45]:
# is a Pandas DataFrame that contains information about the new users, including their user names, the movies they have rated, and their predicted cluster labels.
newUsers

User Jaws Star Wars Exorcist Omen Cluster ID
0   Maina    4         5        1    2          1
1     Tom    3         2        4    4          0
2   Joyce    3         2        4    1          1
3   Kamau    3         2        3    3          0
4  Otieno    5         4        1    4          1